#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2025 Sebastian Andersson <sebastian@bittr.nu>
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Core business logic for create_template_files, separated from CLI concerns.
This module can be used by both CLI and GUI applications.
"""

import json
import os
import shutil
from dataclasses import dataclass
from typing import Callable, Dict, Optional

from file_utils import atomic_write


VERSION = "0.0.2-3-gdf67a39"

ORCASLICER = "orcaslicer"
PRUSASLICER = "prusaslicer"
SLICER = "slic3r"
SUPERSLICER = "superslicer"

DEFAULT_TEMPLATE_SUFFIX = ".template"


@dataclass
class TemplateConfig:
    """Configuration for template file creation"""

    slicer: str
    filament_path: str
    template_path: str
    verbose: bool = False
    delete_all: bool = False

    def __post_init__(self):
        """Validate configuration"""
        if self.slicer not in [ORCASLICER, PRUSASLICER, SLICER, SUPERSLICER]:
            raise ValueError(f"Unsupported slicer: {self.slicer}")


class TemplateProcessor:
    """
    Processes existing slicer configs and creates template files.
    Can be used from CLI or GUI applications.
    """

    def __init__(self, config: TemplateConfig, logger: Optional[Callable] = None):
        """
        Initialize the processor.

        Args:
            config: Configuration object
            logger: Optional callable for logging messages (takes message string and level)
        """
        self.config = config
        self.logger = logger or self._default_logger

    def _default_logger(self, message: str, level: str = "INFO"):
        """Default logger that prints to console"""
        if level == "DEBUG" and not self.config.verbose:
            return
        print(f"{level}: {message}")

    def _log_info(self, message: str):
        """Log an informational message"""
        self.logger(message, "INFO")

    def _log_debug(self, message: str):
        """Log a debug message"""
        if self.config.verbose:
            self.logger(f"DEBUG: {message}", "DEBUG")

    def get_material(self, config: Dict, slicer: str) -> str:
        """Returns the filament config's material"""
        if slicer == ORCASLICER:
            return config.get("filament_type")[0]
        if slicer == SLICER:
            # Slic3r doesn't support materials
            return "default"
        return config.get("filament_type")

    def create_template_path(self):
        """Creates the dir for the template config for the slicer"""
        if not os.path.exists(self.config.template_path):
            self._log_info(f"Creating templates config dir: {self.config.template_path}")
            os.makedirs(self.config.template_path)

    def copy_filament_template_files(self, script_dir: str):
        """Copy the default filename templates, if missing"""
        filename_template_file = f"{self.config.template_path}/filename.template"
        if not os.path.exists(filename_template_file):
            shutil.copy(
                f"{script_dir}/templates-{self.config.slicer}/filename.template",
                filename_template_file,
            )
        filename_template_file = (
            f"{self.config.template_path}/filename_for_spool.template"
        )
        if not os.path.exists(filename_template_file):
            shutil.copy(
                f"{script_dir}/templates-{self.config.slicer}/filename_for_spool.template",
                filename_template_file,
            )

    def read_ini_file(self, filename: str) -> Dict:
        """Reads ini file"""
        config = {}
        with open(filename, "r", encoding="utf-8") as file:
            while line := file.readline():
                if line.startswith("#"):
                    continue
                line = line.rstrip()
                line = line.split("=", 1)
                if len(line) > 1:
                    key = line[0].rstrip()
                    val = line[1].lstrip()
                    config[key] = val
        return config

    def load_config_file(self, slicer: str, filename: str) -> Dict:
        """Load filament config file for slicer"""
        if slicer == ORCASLICER:
            with open(filename, "r", encoding="utf-8") as file:
                config = json.load(file)
        else:
            config = self.read_ini_file(filename)
        return config

    def store_config(self, slicer: str, template_file_name: str, config: Dict):
        """Store the config file"""
        if slicer == ORCASLICER:
            config["_comment"] = "Generated by {{sm2s.name}} {{sm2s.version}}"
            content = json.dumps(config, indent=4)
        else:
            lines = []
            if not template_file_name.endswith(f".info{DEFAULT_TEMPLATE_SUFFIX}"):
                lines.append("# generated by {{sm2s.name}} {{sm2s.version}}\n")
            for key, value in config.items():
                lines.append(f"{key} = {value}\n")
            content = "".join(lines)

        atomic_write(template_file_name, content)

    def update_config_settings(self, slicer: str, config: Dict) -> Dict:
        """Update config settings with template variables"""
        if slicer == ORCASLICER:
            for key, value in {
                "default_filament_colour": ["#{{color_hex}}"],
                "filament_cost": ["{{price}}"],
                "filament_spool_weight": ["{{spool_weight}}"],
                "filament_type": ["{{material}}"],
                "filament_diameter": ["{{diameter}}"],
                "filament_density": ["{{density}}"],
                "filament_settings_id": ["{{id}}"],
                "filament_start_gcode": [
                    "{% if spool.id %}SET_ACTIVE_SPOOL ID={{spool.id}}{% else %}"
                    + "ASSERT_ACTIVE_FILAMENT ID={{id}}{% endif %}"
                ],
                "pressure_advance": ["{{extra.pressure_advance|default(0)|float}}"],
                "filament_vendor": ["{{vendor.name}}"],
                "name": "{% if spool.id %}{{name}} - {{spool.id}}{% else %}{{name}}{% endif %}",
                "nozzle_temperature": ["{{settings_extruder_temp|int}}"],
                "nozzle_temperature_initial_layer": ["{{settings_extruder_temp|int + 5}}"],
                "cool_plate_temp": ["{{settings_bed_temp|int}}"],
                "eng_plate_temp": ["{{settings_bed_temp|int}}"],
                "hot_plate_temp": ["{{settings_bed_temp|int}}"],
                "textured_plate_temp": ["{{settings_bed_temp|int}}"],
                "cool_plate_temp_initial_layer": ["{{settings_bed_temp|int + 10}}"],
                "eng_plate_temp_initial_layer": ["{{settings_bed_temp|int + 10}}"],
                "hot_plate_temp_initial_layer": ["{{settings_bed_temp|int + 10}}"],
                "textured_plate_temp_initial_layer": ["{{settings_bed_temp|int + 10}}"],
            }.items():
                if key in config:
                    config[key] = value
        else:
            for key, value in {
                "bed_temperature": "{{settings_bed_temp|int}}",
                "filament_colour": " #{{color_hex}}",
                "filament_cost": "{{price}}",
                "filament_density": "{{density}}",
                "filament_diameter": "{{diameter}}",
                "filament_settings_id": '"{{id}}"',
                "filament_spool_weight": "{{spool_weight}}",
                "filament_type": "{{material}}",
                "filament_vendor": '"{{vendor.name}}"',
                "first_layer_bed_temperature": "{{settings_bed_temp|int + 10}}",
                "first_layer_temperature": "{{settings_extruder_temp|int + 10}}",
                "start_filament_gcode": '"; Filament gcode\n'
                + "{% if extra.pressure_advace %}"
                + "SET_PRESSURE_ADVANCE ADVANCE="
                + "{{extra.pressure_advance|default(0)|float}}\n{% endif %}"
                + "{% if spool.id %}SET_ACTIVE_SPOOL ID={{spool.id}}"
                + '{% else %}ASSERT_ACTIVE_FILAMENT ID={{id}}{% endif %}\n"',
                "temperature": "{{settings_extruder_temp|int}}",
            }.items():
                if key in config:
                    config[key] = value.replace("\n", "\\n")

        return config

    def process_config_files(self, script_dir: str):  # pylint: disable=unused-argument
        """Process all config files and create templates"""
        if self.config.slicer == ORCASLICER:
            suffix = ".json"
        else:
            suffix = ".ini"

        for filename in os.listdir(self.config.filament_path):
            full_path = f"{self.config.filament_path}/{filename}"
            if not full_path.endswith(suffix):
                continue

            if self.config.slicer == SLICER and full_path.endswith("/My Settings.ini"):
                continue

            self._log_debug(f"Processing {full_path}")
            config = self.load_config_file(self.config.slicer, full_path)
            material = self.get_material(config, self.config.slicer)
            template_file_name = (
                f"{self.config.template_path}/{material}{suffix}{DEFAULT_TEMPLATE_SUFFIX}"
            )

            if os.path.exists(template_file_name):
                self._log_debug(f"Template for {material} already exists, skipping")
                continue

            config = self.update_config_settings(self.config.slicer, config)
            self._log_info(f"Creating file: {template_file_name}")
            self.store_config(self.config.slicer, template_file_name, config)

            if self.config.slicer == ORCASLICER:
                info_filename = full_path.replace(suffix, ".info")
                config = self.load_config_file(SUPERSLICER, info_filename)
                template_file_name = (
                    f"{self.config.template_path}/{material}.info{DEFAULT_TEMPLATE_SUFFIX}"
                )
                self._log_info(f"Creating file: {template_file_name}")
                config["updated_time"] = "{{sm2s.now_int}}"
                self.store_config(SUPERSLICER, template_file_name, config)

    def run(self, script_dir: str):
        """Main entry point to create templates"""
        self.create_template_path()
        self.copy_filament_template_files(script_dir)
        self.process_config_files(script_dir)
