#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2025 Sebastian Andersson <sebastian@bittr.nu>
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Shared fixtures for spoolman2slicer tests
"""

import json
import os
import tempfile
from pathlib import Path

import pytest


@pytest.fixture
def sample_spoolman_response():
    """Sample Spoolman API response with filament data"""
    return [
        {
            "id": 1,
            "filament": {
                "id": 10,
                "registered": "2024-10-08T12:23:04Z",
                "name": "Test PLA Black",
                "vendor": {
                    "id": 5,
                    "registered": "2024-10-08T12:20:15Z",
                    "name": "TestVendor",
                    "extra": {},
                },
                "material": "PLA",
                "price": 25.0,
                "density": 1.24,
                "diameter": 1.75,
                "weight": 1000.0,
                "spool_weight": 200.0,
                "article_number": "PLA-BLK-001",
                "settings_extruder_temp": 210,
                "settings_bed_temp": 60,
                "color_hex": "000000",
                "extra": {"pressure_advance": "0.045"},
            },
        },
        {
            "id": 2,
            "filament": {
                "id": 11,
                "registered": "2024-10-09T10:15:30Z",
                "name": "Test ABS Red",
                "vendor": {
                    "id": 6,
                    "registered": "2024-10-09T10:10:00Z",
                    "name": "AnotherVendor",
                    "extra": {},
                },
                "material": "ABS",
                "price": 30.0,
                "density": 1.04,
                "diameter": 1.75,
                "weight": 1000.0,
                "spool_weight": 250.0,
                "article_number": "ABS-RED-002",
                "settings_extruder_temp": 240,
                "settings_bed_temp": 100,
                "color_hex": "FF0000",
                "extra": {},
            },
        },
    ]


@pytest.fixture
def sample_filament_data():
    """Sample single filament data"""
    return {
        "id": 10,
        "registered": "2024-10-08T12:23:04Z",
        "name": "Test PLA Black",
        "vendor": {
            "id": 5,
            "registered": "2024-10-08T12:20:15Z",
            "name": "TestVendor",
            "extra": {},
        },
        "material": "PLA",
        "price": 25.0,
        "density": 1.24,
        "diameter": 1.75,
        "weight": 1000.0,
        "spool_weight": 200.0,
        "article_number": "PLA-BLK-001",
        "settings_extruder_temp": 210,
        "settings_bed_temp": 60,
        "color_hex": "000000",
        "extra": {"pressure_advance": "0.045"},
    }


@pytest.fixture
def temp_output_dir():
    """Create a temporary directory for file outputs"""
    with tempfile.TemporaryDirectory() as tmpdir:
        yield tmpdir


@pytest.fixture
def temp_template_dir():
    """Create a temporary directory with test templates"""
    with tempfile.TemporaryDirectory() as tmpdir:
        # Create filename template
        filename_template = Path(tmpdir) / "filename.template"
        filename_template.write_text(
            "{% if sm2s.variant != \"\" %}\n"
            "{{sm2s.variant}} - {{vendor.name}} - {{name}}.{{sm2s.slicer_suffix}}\n"
            "{% else %}\n"
            "{{vendor.name}} - {{name}}.{{sm2s.slicer_suffix}}\n"
            "{% endif %}\n"
        )

        # Create default.ini.template for SuperSlicer/PrusaSlicer
        default_ini = Path(tmpdir) / "default.ini.template"
        default_ini.write_text(
            "# generated by {{sm2s.name}} {{sm2s.version}}\n"
            "filament_type = {{material}}\n"
            "filament_colour = #{{color_hex}}\n"
            "filament_cost = {{price}}\n"
            "filament_density = {{density}}\n"
            "filament_diameter = {{diameter}}\n"
            "filament_settings_id = \"{{id}}\"\n"
            "filament_vendor = \"{{vendor.name}}\"\n"
            "temperature = {{settings_extruder_temp|int}}\n"
            "bed_temperature = {{settings_bed_temp|int}}\n"
        )

        # Create default.json.template for OrcaSlicer
        default_json = Path(tmpdir) / "default.json.template"
        default_json.write_text(
            json.dumps(
                {
                    "_comment": "Generated by {{sm2s.name}} {{sm2s.version}}",
                    "name": "{{name}}",
                    "filament_type": ["{{material}}"],
                    "default_filament_colour": ["#{{color_hex}}"],
                    "filament_cost": ["{{price}}"],
                    "filament_density": ["{{density}}"],
                    "filament_diameter": ["{{diameter}}"],
                    "filament_settings_id": ["{{id}}"],
                    "filament_vendor": ["{{vendor.name}}"],
                    "nozzle_temperature": ["{{settings_extruder_temp|int}}"],
                    "cool_plate_temp": ["{{settings_bed_temp|int}}"],
                },
                indent=4,
            )
        )

        # Create default.info.template for OrcaSlicer
        default_info = Path(tmpdir) / "default.info.template"
        default_info.write_text("updated_time = {{sm2s.now_int}}\n")

        # Create PLA.ini.template
        pla_ini = Path(tmpdir) / "PLA.ini.template"
        pla_ini.write_text(
            "# generated by {{sm2s.name}} {{sm2s.version}}\n"
            "filament_type = {{material}}\n"
            "filament_colour = #{{color_hex}}\n"
            "filament_cost = {{price}}\n"
            "temperature = {{settings_extruder_temp|int}}\n"
        )

        yield tmpdir


@pytest.fixture
def temp_config_files():
    """Create temporary config files for testing create_template_files"""
    with tempfile.TemporaryDirectory() as tmpdir:
        # Create sample INI file
        ini_file = Path(tmpdir) / "test_pla.ini"
        ini_file.write_text(
            "# Filament config\n"
            "filament_type = PLA\n"
            "filament_colour = #000000\n"
            "filament_cost = 25.0\n"
            "filament_density = 1.24\n"
            "temperature = 210\n"
            "bed_temperature = 60\n"
        )

        # Create sample JSON file
        json_file = Path(tmpdir) / "test_abs.json"
        json_file.write_text(
            json.dumps(
                {
                    "name": "Test ABS",
                    "filament_type": ["ABS"],
                    "default_filament_colour": ["#FF0000"],
                    "filament_cost": ["30.0"],
                    "filament_density": ["1.04"],
                    "nozzle_temperature": ["240"],
                    "cool_plate_temp": ["100"],
                },
                indent=4,
            )
        )

        yield tmpdir
